name: "Bug Report"
description: "Report a bug with the Obsidian Rose Pine theme"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to report a bug! Please fill out the details below."
  
  - type: checkboxes
    id: checked-updates
    attributes:
      label: "Checked for Updates"
      description: "Have you checked if you are using the latest version of Obsidian and the Rose Pine theme?"
      options:
        - label: "Yes, I have checked for updates and the issue persists."
          required: true

  - type: textarea
    id: plugin
    attributes:
      label: "Plugin"
      description: "If it is a plugin that is effected, please enter the name and author of it"
      placeholder: "Enter name here"

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "Provide a clear and concise description of the bug."
      placeholder: "When I enable the theme, the sidebar text disappears."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce / Example text"
      description: "List the steps needed to reproduce the issue."
      placeholder: "1. Go to Settings > Appearance\n2. Enable the Rose Pine theme\n3. Observe missing text in the sidebar"
  
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain the issue."
      placeholder: "Drag and drop screenshots here."
    validations:
      required: true
      

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Info"
      description: "Any other context, system information, or notes?"
